### ISSUE TITLE
Sync develop branch with master

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [paypal/PPExtensions#40]
**What feature are your requesting?**
Sync develop branch with master, so the future pull requests will go to develop.

**What benefits do you foresee from the feature you are requesting?**
NA

**Potential solution/ideas?**
NA

**Additional context**
Moving all changes from master to develop, so the future pull requests will go to develop.

**Comment by ayushiagarwal** [comment]
Issue fixed in above PR
