### ISSUE TITLE
Enable notebooks scheduling

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [paypal/PPExtensions#49]
**What feature are your requesting?**
Enable notebooks scheduling

**What benefits do you foresee from the feature you are requesting?**
Productionalizing the notebooks. 

**Potential solution/ideas?**
Integrating with a scheduler like airflow.

**Comment by psychemedia** [comment]
Following the original announcement of the open source goodness of these extensions at JupyterCon back in August, has the actual release of the extensions been put on hold indefinitely?

**Comment by ayushiagarwal** [comment]
Hello,

We have already open sourced the PPExtensions in August. To install the extensions , please run:
`pip install ppextensions` 

Once you install you can follow the below instructions to use it:
https://ppextensions.readthedocs.io/en/latest/getting-started/build-ppextensions/

These are the list of features that are currently avaialble:
<img width="955" alt="screen shot 2018-11-13 at 12 23 50 pm" src="https://user-images.githubusercontent.com/13897163/48441018-4e744a00-e73f-11e8-97ac-7760f1592162.png">

Also please note , we already have a PR for Github integration and Scheduling and it would be available  as soon as the PR is merged.

**Comment by psychemedia** [comment]
The Github integration and Scheduling items were what I was interested in... :-)

**Comment by praveenkanamarlapudi** [comment]
#50 enabled both the github and scheduler integration.

**Comment by praveenkanamarlapudi** [comment]
[#52] enables scheduling.
