### ISSUE TITLE
Hive Magic Results are right indented

### ISSUE THREAD

**Issue by Dee-Pac** [paypal/PPExtensions#63]
**Describe the bug**

The results of Hive queries are right indented. It should be left indented as standard output.

**To Reproduce**

%%hive --hive_server 34.66.242.234 --port 10025
show create table tmp

**Expected behavior**

The columns in the results must be right indented.

**Screenshots**

<img width="598" alt="Screen Shot 2019-07-28 at 1 26 29 PM" src="https://user-images.githubusercontent.com/28269443/62012476-a58a4580-b13b-11e9-9608-f7bd1c9448ce.png">

**Potential fix**
<!--- If you are aware of a potential fix, please share the details.

**Comment by praveen-kanamarlapudi** [comment]
Hi @Dee-Pac ,

Jupyter community has made [right-alignment](https://github.com/jupyter/notebook/pull/2534) as default some time ago.

You can make it left aligned by following the [instructions shared](https://github.com/jupyter/notebook/pull/2534#issuecomment-319467135).

**Comment by Dee-Pac** [comment]
That works @praveenkanamarlapudi .
Thanks for the quick response & help !
